### ISSUE TITLE
Jumping caret

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#98] opened 2018-06-07 09:33 UTC
![](https://dzwonsemrish7.cloudfront.net/items/0Y202B0O3o2z0F373H1D/Screen%20Recording%202018-06-07%20at%2011.22%20AM.gif?v=6f4b2fac)

**Comment by wille** [comment] 2018-06-08 11:48
@littlemooon could you assist me with this? I honestly have no clue whats going on. I cannot understand why this component was designed with weird behavior in the first place, why the f would we want to programatically set the caret?

Shady stuff happening here: https://github.com/bitrefill/airfill-widget/blob/master/src/components/UI/ComboInput/index.js#L254

**Comment by littlemooon** [comment] 2018-06-08 12:12
sure thing, ill pick it up next

as discussed with you directly in slack:
- the functionality is over engineered
- we shouldnt be setting the caret
- it would be ideal to get rid of libphonenumber
- at the moment the best solution seems to be to fix the specific error and rewrite later when convenient/prioritised

**Comment by littlemooon** [comment] 2018-06-11 13:22
Fixed by https://github.com/bitrefill/airfill-widget/pull/101

**Closed by littlemooon** 2018-06-11 13:22 UTC
Labels: bug
