### ISSUE TITLE
Custom amount entry cannot be overwritten in widget

### ISSUE THREAD

**Issue by ziggamon** [bitrefill/airfill-widget#9] opened 2017-08-04 15:40 UTC
Currently if you try to erase the value in the custom field it gets overwritten automatically. 

How to reproduce:
Refill +27 (74) 0164951
Try to order 5 ZAR.

**Comment by mrlundis** [comment] 2017-08-07 07:59
Cannot reproduce this in or test setup. This behaviour is however a know issue with using the widget in a preact app due to their buggy implementation of the `defaultValue` prop.

**Comment by ziggamon** [comment] 2017-08-07 09:05
Ok, but can you reproduce it on production?

**Comment by mrlundis** [comment] 2017-08-07 09:25
Nope, can't reproduce in prod either.

**Comment by ziggamon** [comment] 2017-08-07 09:31
Did you try to order 5 ZAR to the above number?

**Comment by mrlundis** [comment] 2017-08-07 09:36
Sorry, my bad! Read number entry for some reason. This is most likely a regression caused by adding support for non-numerical package values. Will fix!

**Comment by mrlundis** [comment] 2017-08-11 08:07
Fixed in 53be6a97ffaeb73cfcaa882dbc2cc562fa8d3c04

**Closed by mrlundis** 2017-08-11 08:07 UTC
